/* auto-generated by NAPI-RS */
/**
 * Per-target emit selection. The `emit` option is the set of artifact
 * families to produce; each entry maps to one or more files.
 */
export type EmitTarget = 'models' | 'angular';
export declare const EmitTarget: {
  readonly Models: 'models';
  readonly Angular: 'angular';
};

export declare function generate(options: GenerateOptions): Promise<GenerateResult>

/**
 * A single generated artifact. `contents` always carries the emitted
 * source; callers that only need on-disk output can pass `outputPath`
 * and ignore the array.
 */
export interface GeneratedArtifact {
  path: string
  contents: string
}

/**
 * Payload attached to every fatal native throw. The JS wrapper in
 * `lib/index.js` upgrades the thrown plain Error into a `GenerateError`
 * (a real JS class that extends Error), copying these own-properties
 * across so consumers can `instanceof GenerateError` and still read
 * `code/subcode/message/path/warnings`.
 *
 * The fatal sits at the top level (`code/subcode/message/path`); pre-fatal
 * warnings ride in `warnings`. `subcode` is set for `PolicyViolation`
 * codes; it is `null` for every other category.
 */
export interface GenerateErrorPayload {
  code: DiagnosticCode
  subcode: DiagnosticSubcode | null
  message: string
  path: string
  warnings: Array<GeneratorDiagnostic>
}

export interface GenerateOptions {
  /**
   * Path to the spec on disk. Mutually exclusive with `input_contents`;
   * the option validator rejects requests that set both or neither.
   */
  inputPath?: string
  /**
   * Raw spec source. When set, `display_path` is required and the
   * 16 MiB byte cap applies to `input_contents.as_bytes().len()`.
   * JS wrapper fills this in for URL inputs.
   */
  inputContents?: string
  /**
   * Banner / diagnostic display string. Required when `input_contents`
   * is set; ignored when `input_path` is set (the existing path
   * normalisation runs in that case).
   */
  displayPath?: string
  /**
   * Decoder hint. Only honoured when `input_contents` is set; combining
   * it with `input_path` is a shape error.
   */
  inputFormat?: InputFormat
  /**
   * Optional. When undefined, generation runs in-memory (no files written).
   * Passing an empty string is rejected at option resolution.
   */
  outputPath?: string
  emit?: Array<EmitTarget>
  mappedTypes?: Array<MappedType>
  /**
   * Per-content-type override of the generated response-decoding kind
   * (`json | blob | text | arrayBuffer`). Read by the normalize stage
   * when picking how a successful response body is decoded.
   */
  responseTypeMapping?: Array<ResponseTypeMapping>
  naming?: NamingConfig
}

export interface GenerateResult {
  summary: GenerateSummary
  diagnostics: Array<GeneratorDiagnostic>
  artifacts: Array<GeneratedArtifact>
}

export interface GenerateSummary {
  /**
   * Display-normalized path of the source spec, as it appears in the
   * generated-artifact banner and in diagnostics' `path` field. Lets
   * consumers correlate a result with the input they passed; the value
   * is the supplied path with separators normalized, never resolved.
   */
  normalizedSourcePath: string
  specVersion: string
  title: string
  pathCount: number
  operationCount: number
  schemaCount: number
}

/**
 * Boundary projection of `Diagnostic` for the NAPI surface — string-typed
 * `code` is what JS consumers see and compare against. `severity` is
 * either `"warning"` or `"error"`; the TS surface narrows it to the
 * `'warning' | 'error'` union via `scripts/patch-types.mjs`. `subcode`
 * is populated only for `PolicyViolation` today; consumers route on it
 * when they need finer-grained remediation than `code` alone.
 */
export interface GeneratorDiagnostic {
  code: DiagnosticCode
  subcode: DiagnosticSubcode | null
  severity: 'warning' | 'error'
  message: string
  path: string
}

/**
 * Explicit decoder selection. Skips both extension-based detection and
 * the JSON-then-YAML sniff fallback. Honoured only with `input_contents`.
 */
export declare const enum InputFormat {
  Json = 'json',
  Yaml = 'yaml'
}

/**
 * Canonical mapped-type record. Used as user input (from CLI/JS options)
 * and as the planning record (after schema-name validation).
 *
 * Field names match the CLI YAML config vocabulary (schema/import/type/
 * alias). `ty` is the Rust-side name; the NAPI surface renames it to
 * `type` so the JS API stays idiomatic.
 */
export interface MappedType {
  schema: string
  import: string
  type: string
  alias?: string
}

export interface NamingChainItem {
  string?: string
  rule?: NamingRuleEntry
}

/**
 * User-facing naming config crossing the NAPI boundary. The JS wrapper
 * in `lib/index.js` unpacks each JS `RegExp` into the `{ source, flags
 * }` shape carried here, so Rust sees pure data on this side.
 */
export interface NamingOptions {
  methodName?: NamingValue
  group?: NamingValue
}

export interface NamingParseSpec {
  source: string
  flags: string
}

export interface NamingRuleEntry {
  from?: string
  parse?: NamingParseSpec
  format?: string
  /** Lowercase per spec: 'camel' | 'pascal' | 'snake' | 'kebab' | 'constant'. */
  case?: string
}

/**
 * Discriminated union: a string shorthand, a single rule, or a chain
 * of rules-or-shorthands. NAPI cannot express true sum types, so we
 * use exclusive fields: exactly one of `string`, `rule`, or `chain`
 * must be set. The JS wrapper enforces this; the Rust validator
 * double-checks at config resolution.
 */
export interface NamingValue {
  /** `{ string: '...' }` — bare format-string shorthand. */
  string?: string
  /** `{ rule: { ... } }` — a single Rule. */
  rule?: NamingRuleEntry
  /**
   * `{ chain: [...] }` — a sequence; each item is an exclusive
   * `{ string }` or `{ rule }`.
   */
  chain?: Array<NamingChainItem>
}

/**
 * JS-facing response-kind values. Mirrors the names Angular's
 * `HttpClient.request({ responseType })` and `httpResource.<kind>()`
 * expose, so the config vocabulary stays in JS conventions. The emit
 * boundary translates `ArrayBuffer` to the lowercase `'arraybuffer'`
 * string `HttpClient.request` requires.
 */
export declare const enum ResponseType {
  Json = 'json',
  Blob = 'blob',
  Text = 'text',
  ArrayBuffer = 'arrayBuffer'
}

/**
 * User mapping: override the response-kind decoded for a specific
 * response content-type. Pure data — Phase-3 normalize-side reads
 * this when picking the `responseKind` for an operation's response
 * content. Keys are matched case-insensitively against the lowercased
 * media-type from the spec; the `responseType` is one of the JS-facing
 * HttpClient response kinds (`'json' | 'blob' | 'text' | 'arrayBuffer'`).
 */
export interface ResponseTypeMapping {
  contentType: string
  responseType: ResponseType
}

// Hand-authored tail concatenated onto the napi-rs-generated index.d.ts
// by scripts/patch-types.mjs. Contains TS surface that napi-rs cannot
// emit on its own (named string-literal unions, the GenerateError class
// defined in lib/index.js).

/**
 * Diagnostic code taxonomy. Each value maps 1:1 to a Rust DiagnosticCode,
 * except `E_UNEXPECTED` and `E_UNSUPPORTED_RUNTIME`, which are reserved
 * for the JS wrapper in `lib/index.js`:
 *   - `E_UNEXPECTED` is a defensive fallback when a `GenerateError` is
 *     constructed without an explicit `code`.
 *   - `E_UNSUPPORTED_RUNTIME` is thrown by `browser.js` when `generate()`
 *     is called in a browser or edge runtime (no native binding available).
 *
 * `E_INVALID_OPTION` covers both wrapper-side shape rejections (a JS
 * caller passed an option whose type/shape is wrong — surfaced with
 * `subcode: 'shape'`) and Rust-side semantic rejections of option values
 * (surfaced with no subcode).
 */
export type DiagnosticCode =
  | 'E_INPUT_INVALID'
  | 'E_UNSUPPORTED_SEMANTIC'
  | 'E_UNSUPPORTED_RUNTIME'
  | 'E_INVALID_REFERENCE'
  | 'E_INVALID_OPTION'
  | 'E_POLICY_VIOLATION'
  | 'E_WRITE_FAILED'
  | 'E_UNEXPECTED';

/**
 * Finer-grained taxonomy projected from `Diagnostic.subcode`. Emitted for
 * `E_POLICY_VIOLATION` diagnostics, a subset of `E_UNSUPPORTED_SEMANTIC`
 * warnings, and wrapper-side `E_INVALID_OPTION` shape rejections
 * (`'shape'`) so consumers can route remediation without parsing the
 * message. Null for every diagnostic that does not carry a sub-class.
 */
export type DiagnosticSubcode =
  | 'shape'
  | 'missing-operation-id'
  | 'missing-tag'
  | 'field-collision'
  | 'missing-discriminator-property'
  | 'unsupported-parameter-location'
  | 'duplicate-operation-id'
  | 'duplicate-schema-name'
  | 'format-dropped'
  | 'schema-cap-exceeded'
  | 'operation-cap-exceeded'
  | 'mapping-expansion-exceeded'
  | 'naming-resolution'
  | 'multi-content-body'
  | 'unsupported-body-content-type'
  | 'multipart-nested-object'
  | 'multipart-composed-field'
  | 'multipart-non-object-body'
  | 'multipart-open-schema'
  | 'urlencoded-binary-field'
  | 'urlencoded-nested-object'
  | 'urlencoded-composed-field'
  | 'urlencoded-non-object-body'
  | 'urlencoded-open-schema';

/**
 * Thrown by `generate` on any fatal diagnostic. Real JS class
 * that extends `Error`, so consumers can write `err instanceof
 * GenerateError`.
 *
 * Defined in `lib/index.js` (not by napi-rs) — the native binding
 * throws a plain Error carrying these own-properties and a marker that
 * the JS wrapper uses to upgrade it.
 */
export declare class GenerateError extends Error {
  constructor(payload: GenerateErrorPayload);
  readonly code: DiagnosticCode;
  readonly subcode: DiagnosticSubcode | null;
  readonly path: string;
  readonly warnings: Array<GeneratorDiagnostic>;

  /**
   * Cross-realm-safe predicate. `instanceof GenerateError` only matches
   * inside the realm where `openapi-ng` was loaded (a different vm
   * context / worker thread / iframe has a different class identity).
   * The internal sentinel survives the realm boundary, so consumers
   * who run across realms should prefer this check.
   */
  static isGenerateError(value: unknown): value is GenerateError;
}

/**
 * Case transformations supported by naming rules (see `docs/naming-spec.md`).
 */
export type Case = 'camel' | 'pascal' | 'snake' | 'kebab' | 'constant';

/**
 * One rule in a naming chain. All four fields are optional. The
 * evaluation order is: expand `from` → match `parse` → expand `format`
 * (defaults to expanded `from` when omitted; required when `parse` is
 * present) → apply `case`. A rule fails when any template reference is
 * unbound or `parse` does not match.
 */
export interface NamingRule {
  from?: string;
  parse?: RegExp;
  format?: string;
  case?: Case;
}

/**
 * A bare string is shorthand for `{ format: string }` with no case
 * transformation. An array is a fallback chain — the first rule that
 * does not fail wins; if every rule fails the generation errors with
 * `E_POLICY_VIOLATION` subcode `'naming-resolution'`.
 */
export type Naming = string | NamingRule | Array<NamingRule | string>;

export interface NamingConfig {
  methodName?: Naming;
  group?: Naming;
}

/**
 * File-config shape — accepted by `.openapi-ng.{yaml,json}`,
 * `openapi-ng.config.{ts,mts,cts,mjs,js,cjs}`, and the `defineConfig`
 * helper. Keys mirror the YAML/JSON surface (`input`/`output`), NOT
 * the programmatic `generate({ inputPath, outputPath, ... })` surface.
 */
export interface Config {
  input?: string;
  output?: string;
  emit?: Array<EmitTarget>;
  mappedTypes?: Array<MappedType>;
  responseTypeMapping?: Array<ResponseTypeMapping>;
  naming?: NamingConfig;
}

/**
 * Identity helper that anchors TypeScript inference for JS/TS configs:
 *   import { defineConfig } from '@avsystem/openapi-ng/config';
 *   export default defineConfig({ input: 'spec.yaml', output: 'out' });
 *
 * Returns its argument unchanged. Has no runtime behaviour.
 *
 * Declared here so the `./config` subpath export resolves to the same
 * `.d.ts` file (one published types surface).
 */
export declare function defineConfig(config: Config): Config;
