// The snapshot storage layout, shared by the regenerator
// (scripts/regen-snapshots.ts) and the reader
// (__test__/generate.snapshot.spec.ts), so the two cannot drift.

import path from 'node:path';

/**
 * The do-not-edit banner, stripped from every stored artifact so snapshots
 * survive a version bump.
 */
export const BANNER_RE =
  /^\/\/ Generated by openapi-ng v[^\n]*\n\/\/ Source: [^\n]*\n\/\/ DO NOT EDIT[^\n]*\n\n/u;

/**
 * Artifacts byte-identical across every success fixture. Each per-fixture
 * directory omits them; their bodies are stored once under
 * `static-template/`.
 */
export const STATIC_TEMPLATE_PATHS: ReadonlySet<string> = new Set([
  'rest.model.ts',
  'rest.util.ts',
  'rest.validate.ts',
]);

/** Directory holding every snapshot, given the repository root. */
export function snapshotDir(repoRoot: string): string {
  return path.join(repoRoot, '__test__', 'snapshots', 'generate-native');
}

/** The emit targets every snapshot is generated with. */
export const SNAPSHOT_EMIT = ['models', 'angular'] as const;
