// The snapshot suite's single source of truth: which fixtures are pinned,
// what each one proves, and how the files are laid out.
//
// Read by the regenerator (scripts/regen-snapshots.ts) and by the reader
// (__test__/generate.snapshot.spec.ts), so neither can drift from the
// other or from test/fixtures/.

import path from 'node:path';

import type { GenerateOptions } from '../../index.js';

/**
 * The do-not-edit banner, stripped from every stored artifact so a
 * snapshot survives a version bump.
 */
export const BANNER_RE =
  /^\/\/ Generated by openapi-ng v[^\n]*\n\/\/ Source: [^\n]*\n\/\/ DO NOT EDIT[^\n]*\n\n/u;

/**
 * Artifacts byte-identical across every success fixture. Each per-fixture
 * directory omits them; their bodies are stored once under
 * `static-template/`.
 */
export const STATIC_TEMPLATE_PATHS: ReadonlySet<string> = new Set([
  'rest.model.ts',
  'rest.util.ts',
  'rest.validate.ts',
]);

/** The emit targets every snapshot is generated with. */
export const SNAPSHOT_EMIT = ['models', 'angular'] as const;

/** Directory holding every snapshot, given the repository root. */
export function snapshotDir(repoRoot: string): string {
  return path.join(repoRoot, '__test__', 'snapshots', 'generate-native');
}

/** A fixture whose output is pinned, and what a change to it would mean. */
export interface SuccessFixture {
  readonly fixture: string;
  /** What this snapshot proves, in the terms a failing diff should be read in. */
  readonly pins: string;
}

/** A fixture whose failure is pinned. */
export interface FailureFixture extends SuccessFixture {
  /** File the payload is stored under, distinguishing runs of one fixture. */
  readonly snapshot: string;
  /** Options the default run does not pass. */
  readonly options?: Partial<GenerateOptions>;
}

export const SUCCESS_FIXTURES: readonly SuccessFixture[] = [
  { fixture: 'additional-properties.openapi.yaml', pins: 'additionalProperties as Record<string, T>' },
  {
    fixture: 'additional-properties-false.openapi.yaml',
    pins: '`additionalProperties: false` is a no-op, unlike the rejected `true`',
  },
  { fixture: 'allof-composition.openapi.yaml', pins: 'allOf as an intersection' },
  {
    fixture: 'anchor-modest.openapi.yaml',
    pins: 'the accept side of the expansion cap: one anchor reused three times',
  },
  { fixture: 'bench-large.openapi.yaml', pins: 'sort order and buffer sizing at 100+ schemas' },
  {
    fixture: 'bench-multi-tag.openapi.yaml',
    pins: 'per-tag service splitting and artifact ordering across many groups',
  },
  {
    fixture: 'body-multipart-mixed-fields.openapi.yaml',
    pins: 'the FormData IIFE across scalar, array, binary and optional fields',
  },
  {
    fixture: 'body-multipart-ref-to-named-object.openapi.yaml',
    pins: 'a `$ref` multipart body inlines its fields and drops the now-unused import',
  },
  {
    fixture: 'body-urlencoded-scalar-and-array.openapi.yaml',
    pins: 'the URLSearchParams IIFE, distinct from FormData',
  },
  { fixture: 'circular-allof.openapi.yaml', pins: 'five allOf layers stay under the depth cap' },
  {
    fixture: 'consumer-forms-and-non-json.openapi.yaml',
    pins: 'form bodies and non-JSON responses together in one spec',
  },
  { fixture: 'cookie-param.openapi.yaml', pins: 'a cookie parameter is dropped with a warning' },
  {
    fixture: 'deprecated-fields.openapi.yaml',
    pins: '`@deprecated` on an operation, a type alias and a property',
  },
  { fixture: 'discriminated-union.openapi.yaml', pins: 'oneOf with a discriminator' },
  {
    fixture: 'discriminator-allof.openapi.yaml',
    pins: 'narrowing reaches the inline part of an allOf-shaped member',
  },
  {
    fixture: 'discriminator-mapping.openapi.yaml',
    pins: 'an explicit mapping key wins over the lowercased schema name',
  },
  { fixture: 'empty-shapes.openapi.yaml', pins: 'an empty object emits Record<string, never>' },
  { fixture: 'errors-typed.openapi.yaml', pins: 'the per-operation error interface keyed by status' },
  { fixture: 'header-param.openapi.yaml', pins: 'the synthetic nested `headers` member' },
  {
    fixture: 'jsdoc-descriptions.openapi.yaml',
    pins: 'descriptions on a type, a property, and a merged operation summary',
  },
  { fixture: 'inline-model.openapi.yaml', pins: 'an inline object body hoists its properties' },
  { fixture: 'large-enum.openapi.yaml', pins: 'both sides of the literal-union width budget' },
  { fixture: 'missing-tag.openapi.yaml', pins: 'a tagless operation groups by its first path segment' },
  { fixture: 'multi-tag-operation.openapi.yaml', pins: 'only the first tag is used for grouping' },
  { fixture: 'multi-warning.openapi.yaml', pins: 'warning order within one operation' },
  { fixture: 'nullable-oneof.openapi.yaml', pins: '`nullable` over a union flattens to `| null`' },
  { fixture: 'nullable-optional.openapi.yaml', pins: 'nullable and optional are independent' },
  { fixture: 'oneof-anyof-composition.openapi.json', pins: 'oneOf and anyOf from a JSON source' },
  { fixture: 'oneof-anyof-composition.openapi.yaml', pins: 'oneOf and anyOf both emit a union' },
  { fixture: 'petstore-minimal.openapi.json', pins: 'the smallest accepted spec, JSON' },
  { fixture: 'petstore-minimal.openapi.yaml', pins: 'the smallest accepted spec, YAML' },
  { fixture: 'petstore-rich.openapi.json', pins: 'the reference spec, JSON' },
  { fixture: 'petstore-rich.openapi.yaml', pins: 'the reference spec, YAML' },
  { fixture: 'recursive-model.openapi.yaml', pins: 'a cycle through a `$ref` property' },
  { fixture: 'recursive-oneof.openapi.yaml', pins: 'a cycle through a union member' },
  {
    fixture: 'reserved-prop-names.openapi.yaml',
    pins: 'a reserved word stays bare while a non-identifier gets quoted',
  },
  { fixture: 'response-204-no-content.openapi.yaml', pins: 'a bodyless response emits `void`' },
  { fixture: 'response-blob-via-pdf.openapi.yaml', pins: '`application/pdf` routes to the blob variant' },
  {
    fixture: 'response-default-fallback.openapi.yaml',
    pins: 'a `default`-only response contributes no success type',
  },
  { fixture: 'response-octet-stream.openapi.yaml', pins: '`application/octet-stream` routes to blob' },
  { fixture: 'response-problem-json.openapi.yaml', pins: 'the `+json` suffix classifies as JSON' },
  { fixture: 'response-text-via-text-plain.openapi.yaml', pins: '`text/plain` routes to the text variant' },
  { fixture: 'security-schemes.openapi.yaml', pins: 'securitySchemes is accepted and ignored' },
  { fixture: 'single-entry-composition.openapi.yaml', pins: 'a one-member composition is its member' },
  { fixture: 'string-formats.openapi.yaml', pins: 'every dropped `format` reports a warning' },
  { fixture: 'verb-prefix.openapi.yaml', pins: 'an operationId already prefixed by its verb' },
];

export const FAILURE_FIXTURES: readonly FailureFixture[] = [
  { fixture: 'additional-properties-boolean.openapi.yaml', pins: '`additionalProperties: true` is rejected' },
  { fixture: 'anchor-fanout.openapi.yaml', pins: 'the reject side of the expansion cap' },
  { fixture: 'body-content-type-xml.openapi.yaml', pins: 'an unsupported body content type' },
  { fixture: 'body-multi-content.openapi.yaml', pins: 'a body declaring more than one content type' },
  { fixture: 'body-multipart-composed-field.openapi.yaml', pins: 'a composed multipart field' },
  { fixture: 'body-multipart-nested-object.openapi.yaml', pins: 'a nested-object multipart field' },
  { fixture: 'body-multipart-non-object.openapi.yaml', pins: 'a non-object multipart body' },
  { fixture: 'body-multipart-open-schema.openapi.yaml', pins: 'an open-ended multipart body' },
  { fixture: 'body-urlencoded-binary-field.openapi.yaml', pins: 'a binary field under urlencoded' },
  { fixture: 'body-urlencoded-nested-object.openapi.yaml', pins: 'a nested-object urlencoded field' },
  { fixture: 'deep-nested-allof.openapi.yaml', pins: 'forty allOf layers exceed the depth cap' },
  { fixture: 'discriminator-mapping-external-ref.openapi.yaml', pins: 'a mapping value that is an external ref' },
  { fixture: 'discriminator-missing-property.openapi.yaml', pins: 'a union member missing its discriminator' },
  { fixture: 'duplicate-operation-id.openapi.yaml', pins: 'two operations sharing an operationId' },
  { fixture: 'duplicate-schema-name.openapi.yaml', pins: 'a repeated key under components.schemas' },
  { fixture: 'empty-parameter.openapi.yaml', pins: 'a parameter with an empty schema' },
  { fixture: 'external-ref.openapi.yaml', pins: 'a `$ref` outside components.schemas' },
  { fixture: 'field-collision.openapi.yaml', pins: 'a hoisted body field colliding with a path parameter' },
  { fixture: 'inline-parameter.openapi.yaml', pins: 'a parameter with an inline object schema' },
  { fixture: 'invalid-enum-type.openapi.yaml', pins: 'an enum on a non-string type' },
  { fixture: 'invalid-enum-value.openapi.json', pins: 'a non-string enum member' },
  { fixture: 'unbalanced-path-template.openapi.yaml', pins: 'an unbalanced brace in a path template' },
  { fixture: 'unsupported-root.yaml', pins: 'components.schemas declared as a sequence' },
  { fixture: 'unsupported-semantic.openapi.yaml', pins: 'additionalProperties combined with properties' },
  { fixture: 'unsupported-trace.openapi.yaml', pins: 'a `trace:` operation is rejected' },
  { fixture: 'warning-then-fatal.openapi.yaml', pins: 'warnings recorded before a fatal are retained' },
  {
    fixture: 'petstore-rich.openapi.yaml',
    snapshot: 'petstore-rich.openapi.yaml.invalid-mapped-type.failure.json',
    pins: 'a mapped type naming a schema the spec does not declare',
    options: { mappedTypes: [{ schema: 'MissingSchema', import: '@demo/x', type: 'Missing' }] },
  },
].map(entry => ({ snapshot: `${entry.fixture}.failure.json`, ...entry }));

/**
 * Fixtures with no snapshot. `malformed.yaml`'s wording follows the YAML
 * parser's own line and column output, which the spec asserts by regex.
 */
export const UNSNAPSHOTTED: readonly string[] = ['malformed.yaml'];
