import test from 'ava';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// Use the wrapper so caught errors are real `GenerateError` instances
// (the failure snapshots pin `warnings`/`path` from the upgraded class
// shape).
import { generate } from '../lib/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, '..');
// Pass fixtures as paths relative to CWD (project root) so display_path
// returns a short, machine-independent path in snapshots and banners.
const fixture = (name: string) => path.join('test', 'fixtures', name);
const snapshot = (name: string) =>
  path.join(repoRoot, '__test__', 'snapshots', 'generate-native', name);

function readJsonSnapshot(name: string) {
  return JSON.parse(fs.readFileSync(snapshot(name), 'utf8'));
}

// Strip the per-version banner from artifact contents so snapshots
// survive version bumps. Keep in sync with BANNER_RE in
// scripts/regen-snapshots.mjs.
const BANNER_RE =
  /^\/\/ Generated by openapi-ng v[^\n]*\n\/\/ Source: [^\n]*\n\/\/ DO NOT EDIT[^\n]*\n\n/u;

// Paths whose contents are byte-identical across every success fixture.
// Listed by path in each per-fixture snapshot but the file bodies live
// once under __test__/snapshots/generate-native/static-template/ — see
// scripts/regen-snapshots.mjs for the storage layout.
const STATIC_TEMPLATE_PATHS = new Set([
  'rest.model.ts',
  'rest.util.ts',
  'rest.validate.ts',
]);
const STATIC_TEMPLATE_DIR = path.join(
  repoRoot,
  '__test__',
  'snapshots',
  'generate-native',
  'static-template',
);

/**
 * Hydrate a path-only success snapshot into the full shape the live
 * `generate` result has: each non-static artifact picks up its
 * `contents` from `<snapshot-dir>/<fixture>/<path>`; static-template
 * artifacts remain path-only because their bodies are pinned in
 * static-template.json and asserted by `staticTemplateArtifacts` below.
 */
function hydrateSuccessSnapshot(fixtureName: string) {
  const snap = readJsonSnapshot(`${fixtureName}.success.json`);
  const siblingsDir = path.join(
    repoRoot,
    '__test__',
    'snapshots',
    'generate-native',
    fixtureName,
  );
  const artifacts = snap.artifacts.map((a: any) => {
    if (STATIC_TEMPLATE_PATHS.has(a.path)) {
      return { path: a.path };
    }
    const filePath = path.join(siblingsDir, a.path);
    const contents = fs.readFileSync(filePath, 'utf8');
    return { path: a.path, contents };
  });
  return { ...snap, artifacts };
}

/**
 * Hydrate the static-template snapshot: list of {path, contents}
 * loaded from <snapshot-dir>/static-template/<path>. Sorted by path so
 * the deep-equal stays insensitive to OS readdir order.
 */
function hydrateStaticTemplate() {
  const snap = readJsonSnapshot('static-template.json');
  const artifacts = snap.artifacts
    .map((a: any) => ({
      path: a.path,
      contents: fs.readFileSync(path.join(STATIC_TEMPLATE_DIR, a.path), 'utf8'),
    }))
    .sort((a: any, b: any) => a.path.localeCompare(b.path));
  return { artifacts };
}

function normalizeSuccessResult(result: any) {
  return {
    ...result,
    artifacts: result.artifacts.map((a: any) => {
      if (STATIC_TEMPLATE_PATHS.has(a.path)) {
        return { path: a.path };
      }
      return {
        ...a,
        contents:
          typeof a.contents === 'string' ? a.contents.replace(BANNER_RE, '') : a.contents,
      };
    }),
  };
}

function staticTemplateArtifacts(result: any) {
  return {
    artifacts: result.artifacts
      .filter((a: any) => STATIC_TEMPLATE_PATHS.has(a.path))
      .map((a: any) => ({ path: a.path, contents: a.contents.replace(BANNER_RE, '') }))
      .sort((a: any, b: any) => a.path.localeCompare(b.path)),
  };
}

async function successResult(name: string, options: Record<string, unknown> = {}) {
  return normalizeSuccessResult(
    await generate({
      inputPath: fixture(name),
      emit: ['models', 'angular'],
      ...options,
    }),
  );
}

async function failurePayload(name: string, options: Record<string, unknown> = {}) {
  try {
    await generate({
      inputPath: fixture(name),
      emit: ['models', 'angular'],
      ...options,
    });
    throw new Error(`Expected ${name} to fail.`);
  } catch (thrown) {
    const e = thrown as any;
    return {
      code: e.code,
      message: e.message,
      path: e.path ?? null,
      warnings: e.warnings ?? [],
    };
  }
}

const successFixtures = [
  'petstore-minimal.openapi.yaml',
  'petstore-minimal.openapi.json',
  'petstore-rich.openapi.yaml',
  'petstore-rich.openapi.json',
  'oneof-anyof-composition.openapi.yaml',
  'oneof-anyof-composition.openapi.json',
  'allof-composition.openapi.yaml',
  'additional-properties.openapi.yaml',
  // additional-properties: false combined with declared `properties`
  // emits the named interface unchanged — OpenAPI semantics treat
  // `false` as "no extras beyond what's declared", which is the
  // default for TypeScript interfaces, so the field is structurally
  // a no-op for our emit. (The `true` form remains rejected — see
  // failureFixtures below.)
  'additional-properties-false.openapi.yaml',
  'recursive-model.openapi.yaml',
  'single-entry-composition.openapi.yaml',
  'empty-shapes.openapi.yaml',
  'inline-model.openapi.yaml',
  'nullable-optional.openapi.yaml',
  // header-param emits a non-fatal warning for the unsupported `header`
  // location; the snapshot pins the full warning shape (code/stage/
  // severity/fatal/message/path) so multi-warning regressions surface
  // here, not via a separate substring assertion (E12).
  'header-param.openapi.yaml',
  // large-enum exercises both branches of the D8 enum-rendering width
  // threshold: 50 values forces multi-line, 2 values stays inline.
  'large-enum.openapi.yaml',
  // multi-tag-operation pins the (currently silent) policy that secondary
  // tags are dropped — operation_grouper.rs uses tags.first() only. If
  // someone later wires multi-tag emission, this snapshot surfaces the
  // change.
  'multi-tag-operation.openapi.yaml',
  // nullable-oneof exercises apply_nullable over composition: a oneOf
  // with `nullable: true` (both at top level and as an inline property
  // shape). Pins how the nullable wrapper combines with union semantics.
  'nullable-oneof.openapi.yaml',
  // security-schemes confirms that components.securitySchemes blocks are
  // silently accepted (no error, no warning) — generation proceeds as if
  // the block were not present. If we ever wire auth-aware emission this
  // snapshot surfaces the change.
  'security-schemes.openapi.yaml',
  // circular-allof exercises the E4 recursion-guard happy path: 5 layers
  // of allOf composition that bottom out at BaseAuditFields. Catches any
  // off-by-one in MAX_NORMALIZE_DEPTH that would falsely fail legit
  // deeply-nested specs.
  'circular-allof.openapi.yaml',
  // discriminated-union pins the TS surface for `oneOf` + `discriminator:`
  // (D11).
  'discriminated-union.openapi.yaml',
  // bench-large is a large realistic spec (100+ schemas, 40+ operations).
  // Adding it to the snapshot suite catches regressions that only surface
  // at scale — sort order changes, buffer sizing issues, etc.
  'bench-large.openapi.yaml',
  // reserved-prop-names pins the identifier-escaping policy: reserved
  // words like `class` stay unquoted (valid TS property names), while
  // digit-first / kebab / dotted / space-containing names get
  // single-quoted via safe_property_name.
  'reserved-prop-names.openapi.yaml',
  // jsdoc-descriptions pins JSDoc preservation: schema description on
  // interface/type alias/enum, per-property description, and
  // operation summary+description merged onto the service member.
  'jsdoc-descriptions.openapi.yaml',
  // multi-warning triggers two normalize-stage cookie-parameter warnings
  // in one operation. Pins the warning order (sessionId before
  // trackingId) so a regression that reorders or coalesces the
  // pipeline's pre-fatal diagnostics surfaces here, not as a silent
  // change.
  'multi-warning.openapi.yaml',
  // deprecated-fields exercises OpenAPI `deprecated: true` mapping to
  // `@deprecated` JSDoc on the emitted operation, top-level type alias
  // (enum), and per-property declaration. Pins the JSDoc emission so a
  // regression that drops the tag surfaces here.
  'deprecated-fields.openapi.yaml',
  // recursive-oneof closes the cycle-handling coverage matrix. The
  // existing fixtures cover cycles via plain `$ref` properties
  // (recursive-model) and bounded deep `allOf` chains (circular-allof);
  // this one pins cycles routed through `oneOf` composition, where the
  // back-edge lands as an unresolved Ref inside a union member.
  'recursive-oneof.openapi.yaml',
  // string-formats exercises the format-dropped warning policy: every
  // schema-level `format` hint (uuid, email, uri, date, date-time)
  // surfaces as an E_UNSUPPORTED_SEMANTIC warning with subcode
  // 'format-dropped'. Pins both the warning text/order and the fact that
  // generation still proceeds with the base type.
  'string-formats.openapi.yaml',
  // discriminator-mapping pins the `discriminator.mapping` honoring policy:
  // when a oneOf carries an explicit wire-value mapping, the narrowed
  // literal on each member must use the mapping key (e.g. `feline`,
  // `canine`) rather than the lowercased schema name. Regressions that
  // ignore `mapping` would emit `'cat'`/`'dog'` here.
  'discriminator-mapping.openapi.yaml',
  // discriminator-allof exercises the `oneOf` + `allOf`-shaped members
  // path: each member composes a shared base (Animal) with a
  // variant-specific tail that redeclares the discriminator property.
  // The Intersection walk must reach into the inline part to narrow
  // `kind` to a single string literal on Cat/Dog.
  'discriminator-allof.openapi.yaml',
  // anchor-modest pins the accept-side boundary of the
  // mapping-expansion-exceeded guard: a small anchor (Audit) reused 3×
  // across composed schemas — the kind of legitimate anchor pattern
  // hand-written specs commonly use. The re-serialised byte ratio stays
  // well under the 50× cap, so this fixture proves the guard does not
  // regress modest anchor use. The reject-side boundary lives in
  // `failureFixtures` as `anchor-fanout.openapi.yaml`.
  'anchor-modest.openapi.yaml',
  // body-multipart-mixed-fields exercises the comprehensive multipart
  // form-body walker: scalar + array-of-scalar + binary + array-of-binary
  // + optional scalar. Pins the FormData IIFE shape (`fd.append(...)`
  // per field, `String(...)` cast for scalars, raw passthrough for
  // binaries, `if (... !== undefined)` guards for optional fields) and
  // the request-interface field types (`Blob | File` and `(Blob | File)[]`).
  'body-multipart-mixed-fields.openapi.yaml',
  // body-multipart-ref-to-named-object verifies the flattened_body_ref
  // import suppression: when a multipart body schema is a top-level $ref
  // to a named object (UploadForm), its properties are inlined as
  // form-fields and the now-redundant UploadForm import is omitted.
  'body-multipart-ref-to-named-object.openapi.yaml',
  // body-urlencoded-scalar-and-array exercises the urlencoded form-body
  // walker: scalar + array-of-scalar. Pins the URLSearchParams IIFE
  // shape (distinct from FormData) and the absence of binary fields
  // (rejected upstream in normalize for urlencoded).
  'body-urlencoded-scalar-and-array.openapi.yaml',
  // response-blob-via-pdf verifies the default response-kind classifier
  // routes `application/pdf` to `Blob` using the `requestFactory.blob<…>(…)` variant.
  'response-blob-via-pdf.openapi.yaml',
  // response-text-via-text-plain verifies the default response-kind
  // classifier routes `text/plain` to `string` using the `requestFactory.text<…>(…)` variant.
  'response-text-via-text-plain.openapi.yaml',
  // response-problem-json verifies the `*+json` suffix rule: a media
  // type like `application/problem+json` classifies as Json (not Blob),
  // so the response is emitted as a typed JSON shape via the default
  // `requestFactory<…>(…)` (no non-JSON variant).
  'response-problem-json.openapi.yaml',
] as const;

for (const fixtureName of successFixtures) {
  test(`generate preserves full success payload snapshot for ${fixtureName}`, async t => {
    t.deepEqual(await successResult(fixtureName), hydrateSuccessSnapshot(fixtureName));
  });
}

// rest.model.ts and rest.util.ts are byte-identical across every success
// fixture. Pin them once here; per-fixture snapshots above keep only the
// `path` for these two artifacts. petstore-minimal is the smallest
// fixture that emits them, so it doubles as the baseline.
test('generate emits stable static-template artifacts (rest.model.ts, rest.util.ts, rest.validate.ts)', async t => {
  const baseline = await generate({
    inputPath: fixture('petstore-minimal.openapi.yaml'),
    emit: ['models', 'angular'],
  });
  t.deepEqual(staticTemplateArtifacts(baseline), hydrateStaticTemplate());
});

// Compile gate: write every success-snapshot's artifacts (plus the static
// templates) to a temp project tree and run `tsc --noEmit` over them.
// Catches regressions where snapshots stay textually stable but the emitted
// TS no longer compiles — e.g. an Angular service that references an
// un-imported response type. Lives in this file (next to the snapshot
// loader) so the inputs the gate type-checks are exactly the snapshots
// committed to disk, not a re-generation that might mask drift.
test('snapshot artifacts type-check under tsc --noEmit', t => {
  const repoNodeModules = path.join(repoRoot, 'node_modules');
  if (!fs.existsSync(path.join(repoNodeModules, 'typescript', 'bin', 'tsc'))) {
    t.fail('node_modules/typescript not installed — run `pnpm install` first');
    return;
  }

  // Co-locate the project tree with the existing angular-consumer fixture
  // so module resolution traverses up to repo node_modules (same path that
  // tsconfig.json's "moduleResolution": "bundler" relies on). Live as a
  // sibling of `generated/` rather than inside it: generate.spec.ts's
  // reset helper recursively wipes `generated/` and would race with this
  // file under AVA's per-file parallelism.
  const compileRoot = path.join(
    repoRoot,
    '__test__',
    'angular-consumer',
    '__snapshot_compile__',
  );
  fs.rmSync(compileRoot, { recursive: true, force: true });
  fs.mkdirSync(compileRoot, { recursive: true });

  const staticArtifacts: Array<{ path: string; contents: string }> =
    hydrateStaticTemplate().artifacts;

  const includeGlobs: string[] = [];
  for (const fixtureName of successFixtures) {
    const snap = hydrateSuccessSnapshot(fixtureName);
    const fixtureDir = path.join(
      compileRoot,
      fixtureName.replace(/[^a-zA-Z0-9_-]+/g, '_'),
    );
    fs.mkdirSync(fixtureDir, { recursive: true });

    for (const artifact of snap.artifacts) {
      // Per-fixture snapshots elide static-template `contents` (only the
      // `path` survives); pull bodies from the shared static-template
      // sibling files via `hydrateStaticTemplate`.
      const contents =
        typeof artifact.contents === 'string'
          ? artifact.contents
          : staticArtifacts.find(a => a.path === artifact.path)?.contents;
      if (contents === undefined) {
        t.fail(`Missing contents for ${artifact.path} in ${fixtureName}`);
        return;
      }
      const filePath = path.join(fixtureDir, artifact.path);
      fs.mkdirSync(path.dirname(filePath), { recursive: true });
      fs.writeFileSync(filePath, contents, 'utf8');
    }
    includeGlobs.push(`${path.basename(fixtureDir)}/**/*.ts`);
  }

  const compileTsconfig = {
    extends: '../tsconfig.json',
    include: includeGlobs,
  };
  fs.writeFileSync(
    path.join(compileRoot, 'tsconfig.json'),
    JSON.stringify(compileTsconfig, null, 2),
    'utf8',
  );

  execFileSync(
    process.execPath,
    [path.join(repoNodeModules, 'typescript', 'bin', 'tsc'), '-p', compileRoot],
    {
      cwd: compileRoot,
      stdio: 'pipe',
    },
  );
  t.pass('tsc --noEmit succeeded on every success-snapshot artifact set');
});

const failureFixtures = [
  'unsupported-semantic.openapi.yaml',
  'unsupported-root.yaml',
  'empty-parameter.openapi.yaml',
  'inline-parameter.openapi.yaml',
  'invalid-enum-type.openapi.yaml',
  'invalid-enum-value.openapi.json',
  // additional-properties: true (boolean form, not a schema object) is
  // explicitly rejected at normalize/schema.rs. Snapshot pins the
  // unsupported-subset diagnostic shape.
  'additional-properties-boolean.openapi.yaml',
  // External $ref like 'shared.yaml#/...' is rejected at
  // normalize/schema.rs's normalize_reference. Snapshot pins the
  // unsupported-reference message format.
  'external-ref.openapi.yaml',
  // field-collision pins the field-collision policy under smart-flatten:
  // an inline-object body whose property name duplicates a path/query
  // param is rejected, because hoisting the property to top-level would
  // produce a duplicate field on the request interface. The author's
  // escape hatch is to either rename the property or hoist the body to a
  // named $ref (which nests under `body` instead of flattening).
  'field-collision.openapi.yaml',
  // deep-nested-allof exercises the MAX_NORMALIZE_DEPTH guard at 40
  // levels of inline allOf nesting. Pins the unsupported-semantic
  // diagnostic so a regression that removes the guard or shifts the
  // error code surfaces here, not just in the targeted spec test.
  'deep-nested-allof.openapi.yaml',
  // unbalanced-path-template exercises the normalize-stage path string
  // validation: paths with unmatched `{` / `}` would otherwise reach
  // the emit stage and produce a broken TypeScript template
  // (`url: `/pets/id`` with no `${encodeURIComponent(id)}` expansion).
  'unbalanced-path-template.openapi.yaml',
  // discriminator-mapping-external-ref pins the normalize-stage
  // rejection of a mapping value whose ref shape is not an internal
  // `#/components/schemas/` ref. Without routing the mapping resolution
  // through `normalize_reference`, an external URL like
  // `http://example.com/schemas/Cat` would silently pass as a bare
  // literal that never matches any union member.
  'discriminator-mapping-external-ref.openapi.yaml',
  // anchor-fanout pins the reject-side boundary of the
  // mapping-expansion-exceeded guard: a ~45 KB source whose 500 schemas
  // × 16 anchor aliases each re-serialise into ~15 MB of inlined node
  // tree (~340× ratio). The guard rejects the input at decode time
  // before any normalize/emit work runs. Without this guard, the
  // expanded tree would be carried through the entire pipeline and
  // surface as a slowdown or memory blow-up rather than a clean
  // diagnostic.
  'anchor-fanout.openapi.yaml',
  // Policy-violation subcodes introduced in Phase 4 for multipart /
  // urlencoded form bodies and unsupported content types. One fixture per
  // subcode; each pins the diagnostic so a regression that renames a
  // subcode or routes a reject path through a different arm surfaces here.
  'body-multi-content.openapi.yaml',
  'body-content-type-xml.openapi.yaml',
  'body-multipart-nested-object.openapi.yaml',
  'body-multipart-composed-field.openapi.yaml',
  'body-multipart-non-object.openapi.yaml',
  'body-multipart-open-schema.openapi.yaml',
  'body-urlencoded-binary-field.openapi.yaml',
  'body-urlencoded-nested-object.openapi.yaml',
] as const;

for (const fixtureName of failureFixtures) {
  test(`generate preserves full failure payload snapshot for ${fixtureName}`, async t => {
    t.deepEqual(
      await failurePayload(fixtureName),
      readJsonSnapshot(`${fixtureName}.failure.json`),
    );
  });
}

// malformed.yaml: pin code/path but use a regex on the message so
// upstream serde_yml line/column wording changes don't churn the snapshot.
test('generate preserves stable failure shape for malformed.yaml (regex message)', async t => {
  const payload = await failurePayload('malformed.yaml');
  t.is(payload.code, 'E_INPUT_INVALID');
  t.regex(payload.message, /^Failed to decode OpenAPI input as YAML:/);
  t.true((payload.path ?? '').endsWith('test/fixtures/malformed.yaml'));
  // No pre-fatal warnings expected for a decode-stage failure.
  t.deepEqual(payload.warnings, []);
});

test('generate preserves full failure payload snapshot for invalid mapped type option', async t => {
  t.deepEqual(
    await failurePayload('petstore-rich.openapi.yaml', {
      mappedTypes: [
        {
          schema: 'MissingSchema',
          import: '@demo/x',
          type: 'Missing',
        },
      ],
    }),
    readJsonSnapshot('petstore-rich.openapi.yaml.invalid-mapped-type.failure.json'),
  );
});
