pub(crate) mod angular;
mod emitter;
pub(crate) mod model;
pub(crate) mod ts;

pub(crate) use emitter::emitters_for;

#[cfg(test)]
mod ts_tests;

/// Public path of the generated TypeScript model artifact.
pub(crate) const MODEL_ARTIFACT_PATH: &str = "model.generated.ts";

/// Compile-time crate version for the do-not-edit banner. Sourced from
/// Cargo.toml (the same value `package.json:3` mirrors).
const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Builds the three-line banner every generated artifact opens with:
///
/// ```text
/// // Generated by openapi-ng vX.Y.Z
/// // Source: <source_path>
/// // DO NOT EDIT — regenerate with `openapi-ng generate`
/// ```
///
/// A `source_path` inside the working directory is relativised against
/// it, keeping the local directory layout out of a committed artifact.
/// One outside stays absolute, as does any path when the working
/// directory is unknown.
pub(crate) fn render_generated_banner(source_path: &str) -> String {
  let display = relativise_against_cwd(source_path);
  format!(
    "// Generated by openapi-ng v{GENERATOR_VERSION}\n// Source: {display}\n// DO NOT EDIT — regenerate with `openapi-ng generate`\n\n"
  )
}

/// Relativise an input path against the current working directory.
/// Returns the input unchanged when:
///   - the input is not absolute (already relative — caller's call), or
///   - the host cwd is unknown (e.g. CWD was deleted), or
///   - `strip_prefix` fails (path lives outside CWD).
///
/// Uses forward slashes on the result so banner format stays
/// platform-independent and matches `pipeline::generate`'s display-path
/// normalization.
fn relativise_against_cwd(source_path: &str) -> String {
  use crate::io::host_cwd::host_cwd;
  use std::path::Path;
  let input = Path::new(source_path);
  if !input.is_absolute() {
    return source_path.to_owned();
  }
  let Some(cwd) = host_cwd() else {
    return source_path.to_owned();
  };
  input.strip_prefix(&cwd).map_or_else(
    |_| source_path.to_owned(),
    |rel| rel.to_string_lossy().replace('\\', "/"),
  )
}

#[cfg(test)]
mod banner_tests {
  use super::render_generated_banner;
  use proptest::prelude::*;

  #[test]
  fn banner_includes_generator_name_version_source_and_do_not_edit_marker() {
    let banner = render_generated_banner("./spec.yaml");
    assert!(banner.contains("Generated by openapi-ng v"));
    assert!(banner.contains("Source: ./spec.yaml"));
    assert!(banner.contains("DO NOT EDIT"));
    assert!(banner.contains("openapi-ng generate"));
    assert!(
      banner.ends_with("\n\n"),
      "banner must terminate with a blank line"
    );
  }

  #[test]
  fn banner_version_matches_cargo_pkg_version() {
    let banner = render_generated_banner("ignored");
    let expected = env!("CARGO_PKG_VERSION");
    assert!(banner.contains(&format!("v{expected}")));
  }

  /// An absolute path inside the working directory must render relative,
  /// so no local directory prefix reaches a committed artifact.
  #[test]
  fn banner_relativises_paths_inside_cwd() {
    let cwd = std::env::current_dir().unwrap();
    let absolute_inside = cwd.join("test/fixtures/petstore-minimal.openapi.yaml");
    let banner = render_generated_banner(&absolute_inside.to_string_lossy());
    assert!(
      banner.contains("Source: test/fixtures/petstore-minimal.openapi.yaml"),
      "expected relative path in banner, got: {banner}"
    );
    let cwd_prefix = cwd.to_string_lossy().replace('\\', "/");
    assert!(
      !banner.contains(&*cwd_prefix),
      "absolute CWD prefix leaked into banner: {banner}"
    );
  }

  /// Paths outside CWD are left absolute — `strip_prefix` fails for
  /// them, and rewriting them would break the read-side path passed
  /// elsewhere if anything ever shared this string. Keeps the
  /// "leak limited to spec outside project root" semantics that the
  /// old JS function documented.
  #[test]
  fn banner_keeps_paths_outside_cwd_absolute() {
    // Pick a path that's guaranteed not to be under CWD across all
    // platforms the project supports. On Unix `/nonexistent-outside-cwd`
    // is absolute; on Windows the leading `/` still makes it absolute
    // relative to the current drive — and it won't share the CWD prefix
    // unless someone runs cargo from `/`.
    let outside = "/nonexistent-outside-cwd/external.yaml";
    let banner = render_generated_banner(outside);
    assert!(
      banner.contains(&format!("Source: {outside}")),
      "expected absolute path preserved in banner, got: {banner}"
    );
  }

  /// Already-relative paths must pass through untouched. The banner
  /// must not turn `./spec.yaml` into an empty string or prepend `./`
  /// in surprising ways.
  #[test]
  fn banner_passes_relative_paths_through() {
    let banner = render_generated_banner("./spec.yaml");
    assert!(
      banner.contains("Source: ./spec.yaml"),
      "expected relative input preserved verbatim, got: {banner}"
    );
  }

  /// Rust-side equivalent of the banner-strip regex used by the JS
  /// snapshot test (`BANNER_RE` in __test__/generate.snapshot.spec.ts and
  /// scripts/regen-snapshots.mjs). Kept here so a `proptest` round-trip
  /// across the full source-path input space surfaces drift between the
  /// Rust banner writer and the JS strip regex.
  fn strip_banner(input: &str) -> Option<&str> {
    let first = input.find('\n')?;
    let line1 = &input[..first];
    if !line1.starts_with("// Generated by openapi-ng v") {
      return None;
    }
    let after_line1 = &input[first + 1..];
    let second = after_line1.find('\n')?;
    let line2 = &after_line1[..second];
    if !line2.starts_with("// Source: ") {
      return None;
    }
    let after_line2 = &after_line1[second + 1..];
    let third = after_line2.find('\n')?;
    let line3 = &after_line2[..third];
    if !line3.starts_with("// DO NOT EDIT") {
      return None;
    }
    // Banner ends with a blank line (\n\n), so the next byte must be a
    // newline before the artifact body begins.
    let after_line3 = &after_line2[third + 1..];
    if !after_line3.starts_with('\n') {
      return None;
    }
    Some(&after_line3[1..])
  }

  proptest! {
    /// Any non-newline source path produces a 3-line banner that
    /// `strip_banner` can remove, leaving the original body intact. This
    /// pins the shape of `render_generated_banner` against the strip
    /// regex on the JS side: when this proptest fails, the JS regex
    /// almost certainly needs to be updated too.
    #[test]
    fn render_then_strip_banner_returns_original_body(
      source in "[^\n]{0,64}",
      body in proptest::string::string_regex(".{0,128}").unwrap(),
    ) {
      let banner = render_generated_banner(&source);
      let combined = format!("{banner}{body}");
      let stripped = strip_banner(&combined)
        .ok_or_else(|| proptest::test_runner::TestCaseError::fail(
          format!("strip_banner could not consume the rendered banner for source={source:?}")
        ))?;
      prop_assert_eq!(stripped, body.as_str());
    }
  }
}
